version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PRODUCTION=true
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/flask-starter-kit
      - SECRET_KEY=SECRET_KEY_1
      - SERIALIZER_SECRET_KEY=SECRET_KEY_2
      - MAIL_SERVER=your_mail_server
      - MAIL_USERNAME=your_username
      - MAIL_PASSWORD=your_password
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=SuperSecutrePassword123$
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data: