version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  # celery_worker:
  #   build:
  #     context: .
  #     dockerfile: celery.Dockerfile
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo
  #     - rabbit
  #   restart: unless-stopped

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=SuperSecutrePassword123$
    depends_on:
      - mongo
    restart: unless-stopped

  # rabbit:
  #   hostname: rabbit
  #   image: "rabbitmq:management"
  #   ports:
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: "admin"
  #     RABBITMQ_DEFAULT_PASS: "password"
  #   volumes:
  #     - rabbit_data:/var/lib/rabbitmq
  #   restart: unless-stopped

  # flower: TODO ADD

volumes:
  mongo_data: